on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  # Make sure rustc errors on warnings in the CI
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust-test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, windows, macos]

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      # Marker is required for UI tests
      - uses: rust-marker/marker@v0.3
        with:
          install-only: true

      - run: cargo test --locked

  rust-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # rustfmt, might change some formatting between versions. This check should
      # use the toolchain version from `rust-toolchain.toml` since that is also the
      # version invoked during normal development in the repo. The formatting
      # shouldn't matter for consumers of Marker. Therefore it's safe to use the
      # nightly version of rustfmt
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt --check

  rust-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: rust-marker/marker@v0.3
        with:
          install-only: true

      - run: cargo clippy --all-features --all-targets --locked
      - run: cargo doc --no-deps
      - run: cargo marker -- --all-features --all-targets --locked
